USE REGISTRO;
GO

CREATE TABLE MANTENIMIENTO_CLIENTE(
	ID INT PRIMARY KEY NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Celular INT NOT NULL,
	Correo VARCHAR(50)
);

CREATE TABLE MANTENIMIENTO_VEHICULAR (
	ID INT PRIMARY KEY NOT NULL,  -- clave primaria
	Placa VARCHAR(10) NOT NULL,
	Año_fabricacion INT NULL,
	Color VARCHAR(10) NULL,
	Dueño VARCHAR(50) NOT NULL,
	ClienteID INT NOT NULL  -- llave foránea
);

ALTER TABLE MANTENIMIENTO_VEHICULAR
ADD CONSTRAINT FK_VEHICULAR_CLIENTE
FOREIGN KEY (ClienteID) REFERENCES MANTENIMIENTO_CLIENTE(ID);
